const store={records:JSON.parse(localStorage.getItem('bodyos-records')||'null')||[
['Blood test results available','Laboratory','NHS Pathology','23 Jul 2026'],['Dental panoramic X-ray','Imaging','Hampshire Dental','14 Jul 2026'],['Annual GP health review','Clinical note','NHS GP record','02 Jul 2026'],['Lipid profile','Laboratory','University Hospital','20 Jun 2026']],meds:JSON.parse(localStorage.getItem('bodyos-meds')||'null')||[['Atorvastatin','20 mg','Once daily','20:00'],['Vitamin D3','1,000 IU','Once daily','Tomorrow'],['Aspirin','75 mg','Once daily','20:00']]};
const metrics=[['♥','Heart Rate','62','bpm','Range: 52–102 bpm','#0877F9','8,35 20,29 31,31 43,18 54,22 65,11 77,17 91,8'],['◔','Sleep','7h 48m','','Goal: 7–9h','#67A8FF','8,35 20,12 31,31 43,17 54,24 65,39 77,9 91,27'],['↗','Activity','8,543','steps','Goal: 10,000 steps','#17B978','8,35 20,31 31,18 43,24 54,10 65,16 77,12 91,4'],['♡','Blood Pressure','118/76','mmHg','Normal','#7868F6','8,32 20,23 31,29 43,15 54,24 65,18 77,28 91,13'],['♡','HRV','56','ms','Baseline: 45–65 ms','#0877F9','8,36 20,29 31,33 43,19 54,25 65,11 77,17 91,5']];
const events=[['♡','Blood test results available','Cholesterol, Liver Function, HbA1c','Today, 08:30'],['◔','Sleep data synced','With Apple Health','Today, 07:45'],['◇','Medication logged','Vitamin D3 2000 IU','Yesterday, 21:00'],['❉','Mindful breathing completed','5 minutes','Yesterday, 18:30'],['↗','Cardio workout','Outdoor run · 5.2 km','Yesterday, 07:15']];
const labs=[['Cholesterol','5.1','mmol/L','Normal'],['HbA1c','5.4','%','Normal'],['Vitamin D','62','nmol/L','Optimal'],['CRP','1.2','mg/L','Normal'],['Ferritin','87','µg/L','Normal']];
const sources=[['♥','Apple Health'],['NHS','NHS'],['◉','Oura Ring'],['⌁','Withings Scale']];
const save=()=>{localStorage.setItem('bodyos-records',JSON.stringify(store.records));localStorage.setItem('bodyos-meds',JSON.stringify(store.meds))};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chart(points,color){return `<svg viewBox="0 0 100 45" preserveAspectRatio="none"><polyline points="${points}" fill="none" stroke="${color}" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="91" cy="${points.split(' ').pop().split(',')[1]}" r="2.4" fill="${color}"/></svg>`}
function render(){document.getElementById('metrics').innerHTML=metrics.map(m=>`<article class="card metric"><div class="metric-head"><span class="bubble">${m[0]}</span>${m[1]}</div><strong>${m[2]} <small>${m[3]}</small></strong><div class="chart">${chart(m[6],m[5])}</div><div class="footnote">${m[4]}</div></article>`).join('');
 document.getElementById('events').innerHTML=events.map(e=>`<div class="event"><div class="event-icon">${e[0]}</div><div class="event-copy"><strong>${e[1]}</strong><span>${e[2]}</span></div><time>${e[3]}</time></div>`).join('');
 const labsHtml=labs.map((l,i)=>`<div class="lab"><label>${l[0]}</label><strong>${l[1]} <small>${l[2]}</small></strong><small>${l[3]}</small><div class="mini">${chart('5,22 18,20 31,23 43,16 55,20 67,13 79,14 93,'+(7+i*2),'#17B978')}</div></div>`).join('');
 document.getElementById('labgrid').innerHTML=labsHtml;document.getElementById('labgridFull').innerHTML=labsHtml;
 const src=sources.map(s=>`<div class="connection"><div class="source-icon">${s[0]}</div><div class="source-copy"><strong>${s[1]}</strong><span>Connected</span></div><span>›</span></div>`).join('');document.getElementById('sources').innerHTML=src;
 document.getElementById('connectionGrid').innerHTML=sources.map(s=>`<article class="card med"><div class="source-icon">${s[0]}</div><h3>${s[1]}</h3><p>Connected and contributing current health data.</p><footer><span class="good">Connected</span><button class="btn">Manage</button></footer></article>`).join('');
 document.getElementById('recordRows').innerHTML=store.records.map(r=>`<tr><td><strong>${esc(r[0])}</strong></td><td><span class="pill">${esc(r[1])}</span></td><td>${esc(r[2])}</td><td>${esc(r[3])}</td></tr>`).join('');
 document.getElementById('timelineFull').innerHTML=store.records.map((r,i)=>`<div class="event"><div class="event-icon">${i%2?'▣':'♡'}</div><div class="event-copy"><strong>${esc(r[0])}</strong><span>${esc(r[2])} · ${esc(r[1])}</span></div><time>${esc(r[3])}</time></div>`).join('');
 document.getElementById('medgrid').innerHTML=store.meds.map(m=>`<article class="card med"><div class="bubble">◇</div><h3>${esc(m[0])}</h3><p>${esc(m[1])} · ${esc(m[2])}</p><footer><span>Next dose</span><strong>${esc(m[3])}</strong></footer></article>`).join('');}
function go(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('sidebar').classList.remove('open');window.scrollTo(0,0)}
function toast(msg){const t=document.getElementById('toast');t.innerHTML=`<div class="toast">${msg}</div>`;setTimeout(()=>t.innerHTML='',2500)}
function modal(type){let body='';if(type==='record')body=`<h2>Add health record</h2><div class="field"><label>Record name</label><input id="f1" placeholder="e.g. MRI report"></div><div class="field"><label>Category</label><select id="f2"><option>Clinical note</option><option>Laboratory</option><option>Imaging</option><option>Vaccination</option></select></div><div class="field"><label>Provider</label><input id="f3" placeholder="Provider"></div>`;if(type==='med')body=`<h2>Add medication</h2><div class="field"><label>Name</label><input id="f1"></div><div class="field"><label>Dose</label><input id="f2"></div><div class="field"><label>Schedule</label><input id="f3" value="Once daily"></div>`;if(type==='connect')body=`<h2>Connect health data</h2><p style="color:var(--muted)">Choose a demonstration source. Production connections require provider authentication and explicit consent.</p><div class="field"><label>Source</label><select id="f1"><option>Apple Health</option><option>NHS</option><option>Oura Ring</option><option>Withings</option><option>Garmin</option></select></div>`;document.getElementById('modal').innerHTML=`<div class="modalback"><div class="modal">${body}<div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" data-save="${type}">Save</button></div></div></div>`}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)go(nav.dataset.view);const link=e.target.closest('[data-view-link]');if(link)go(link.dataset.viewLink);if(e.target.closest('#menu'))document.getElementById('sidebar').classList.toggle('open');const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(['record','med','connect'].includes(x))modal(x);if(x==='ask'){document.getElementById('answer').innerHTML='<div class="insight"><strong>AI observation</strong><p>Your sleep duration has increased while resting heart rate has remained stable. This is an observation from demonstration data, not a diagnosis.</p><span class="link">Sources: sleep and heart-rate metrics</span></div>'}if(x==='export'){const blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const d=document.createElement('a');d.href=u;d.download='body-os-health-data.json';d.click();URL.revokeObjectURL(u);toast('Your Body OS data was exported')}}if(e.target.closest('[data-close]'))document.getElementById('modal').innerHTML='';const saveBtn=e.target.closest('[data-save]');if(saveBtn){const type=saveBtn.dataset.save;const f1=document.getElementById('f1')?.value.trim(),f2=document.getElementById('f2')?.value.trim(),f3=document.getElementById('f3')?.value.trim();if(!f1)return toast('Please enter a value');if(type==='record')store.records.unshift([f1,f2||'Clinical note',f3||'Personal upload',new Date().toLocaleDateString('en-GB')]);if(type==='med')store.meds.push([f1,f2||'Dose not set',f3||'As directed','Not scheduled']);save();render();document.getElementById('modal').innerHTML='';toast(type==='connect'?`${f1} connected (demo)`:'Saved to Body OS')}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));render();
